version: '3.9'

services:
  backend:
    image: be_qa:3003
    container_name: fastapi_app
    command: bash -c "
        pip install python-jose[cryptography]
        && python app.py 
      "
    volumes:
      - ./App/backend/src:/app
      - ./pretrained:/root/.cache/huggingface/hub/
    depends_on:
      - redis
      - mongo
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis_server:6379/0
      MONGODB_URL: ${MONGODB_URL}
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      COLLECTION_NAME: ${COLLECTION_NAME}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    ports:
      - "8002:8002"

  worker:
    image: be_qa:3003
    container_name: worker
    command: celery -A tasks.celery_app worker --pool=solo --loglevel=warning
    volumes:
      - ./App/backend/src:/app
      - ./pretrained:/root/.cache/huggingface/hub/
    depends_on:
      - redis
      - mongo
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis_server:6379/0
      MONGODB_URL: ${MONGODB_URL}
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      COLLECTION_NAME: ${COLLECTION_NAME}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      MONGODB_ADMIN_URL: ${MONGODB_ADMIN_URL}
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    # ports:
    #   - "8000:8000"


  redis:
    image: redis:6.2-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
  
  ui:
    image: ui:3003
    container_name: ui
    command: streamlit run main.py --server.port 8501
    volumes:
      - ./App/chatbot-ui:/app
      - ./pretrained:/root/.cache/huggingface/hub/
    ports:
      - "8501:8501"


  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
