version: '3.9'

services:
  backend:
    image: qa:2403
    container_name: fastapi_app
    command: python app.py 
    volumes:
      - ./backend/src:/app
    depends_on:
      - redis
      - mongo
    environment:
      - REDIS_URL=redis://redis_server:6379/0
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - TAVILY_API_KEY=$TAVILY_API_KEY
    ports:
      - "8002:8002"

  worker:
    image: qa:2403
    container_name: worker
    command: celery -A tasks.celery_app worker --loglevel=debug
    volumes:
      - ./backend/src:/app
    depends_on:
      - redis
      - mongo
    environment:
      - REDIS_URL=redis://redis_server:6379/0
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - TAVILY_API_KEY=$TAVILY_API_KEY
    # ports:
    #   - "8000:8000"


  redis:
    image: redis:6.2-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
  
  ui:
    image: ui:2503
    container_name: ui
    ports:
      - "8051:8051"


  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
